version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emails_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
